### ISSUE TITLE
GoPro Hero5 video GPS metadata - 0

### ISSUE THREAD

**Issue by kuku131** [gopro/gpmf-parser#10]
Hi David,

We experienced an issue with GoPro GPS logging where the GPS coordinates captured are 0,0. Can you please advise what may cause this? Is it because user doesn't have good GPS signal (e.g: indoor) and GoPro camera fails to retrieve GPS data?

Thanks!

Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
This is a GoPro with the GPS turned on for the first time, but without a GPS lock. Once the GPS lock is established the zeros go away, forever.  The last successful lock coordinates are saved and used whenever lock is not available.  This is a good question for the FAQ.
