### ISSUE TITLE
memory resource leak in OpenMP4Source()

### ISSUE THREAD

**Issue by invd** [gopro/gpmf-parser#101]
The `OpenMP4Source()` function does not free the malloc()'ed memory for 
https://github.com/gopro/gpmf-parser/blob/98aff124b6b5d01b42da2d0ffada4ea99758929f/demo/GPMF_mp4reader.c#L155

when it is called with a MP4 input file that is smaller than 64 byte. This is due to the abort condition that misses a `free(mp4)`:

https://github.com/gopro/gpmf-parser/blob/98aff124b6b5d01b42da2d0ffada4ea99758929f/demo/GPMF_mp4reader.c#L169

This problem should not have any impact in practice since the caller will likely abort early and the memory will be reclaimed on program exit.

**Comment by dnewman-gpsw** [comment]
Thanks, I have just fixed in on the develop branch.
