### ISSUE TITLE
memory resource leak via uncompressedSamples buffer in GPMF_ScaledData()

### ISSUE THREAD

**Issue by invd** [gopro/gpmf-parser#104]
`uncompressedSamples` is allocated here:
https://github.com/gopro/gpmf-parser/blob/2cc0af7ffee6f12934e2d57750bdf292f62b0a97/GPMF_parser.c#L1388

The `free()` is supposed to happen during the cleanup:
https://github.com/gopro/gpmf-parser/blob/2cc0af7ffee6f12934e2d57750bdf292f62b0a97/GPMF_parser.c#L1702-L1704

However, a lot of code paths in this function directly call `return` instead of assigning `ret` and jumping to `cleanup`, which leaks the memory ressources of `uncompressedSamples`. 

Similar to #103, this is likely not a significant problem for short program runs, but it can become a limiting factor for long-running processes.

**Comment by dnewman-gpsw** [comment]
Good find.  Fixed on the develop branch.  Moving to master shortly.
