### ISSUE TITLE
GRAV data with zeros

### ISSUE THREAD

**Issue by camilosoto93** [gopro/gpmf-parser#110]
Hi, 
I’m doing some test with a HERO8, but I can’t extract a value of GRAV other than zeros: GRAV 0.000, 0.000, 0.000,

I have tried to use the telemetry extractor application too. I have configured the camera in all possible ways but i alway obtain zeros in the GRAV field. I have also tested the camera with GPS fix but i can’t get Gravity values.

Has anyone else had this issue? Does the camera need a special configuration to get the GRAV data? or coud the problem be related to the parsing of the data (i’m using a version of the demo of the gpmf-parser and the goprotelemetryextractor application to parse the GRAV field) ?

Thank you!

**Comment by dnewman-gpsw** [comment]
It is a camera bug.  Only MAX has correct GRAV track, where the values are non-zero.  For some reason the they left the incomplete track active on HERO8.
