### ISSUE TITLE
Update documentation for Hero 9

### ISSUE THREAD

**Issue by dustin** [gopro/gpmf-parser#111]
I've got a [GPMF parser](https://dustin.github.io/gpmf/) for Haskell that I use in some of my projects and want to make sure that if anything interesting was added in Hero 9, that I've considered it.  My library supports GPMF in general at a low level, but I've got a bit of higher level abstractions I bubble up where it's interesting.

**Comment by dnewman-gpsw** [comment]
HERO9 incorporates features from GoPro MAX.  The main addition to HERO9 from MAX is the GRAV stream that stores the gravity vector, useful for post horizon leveling.

**Comment by dnewman-gpsw** [comment]
Nothing user facing, but I've added MKSP and LSKPP streaming data information.
