### ISSUE TITLE
Hero 9 Black

### ISSUE THREAD

**Issue by HaberlElectronic-Max** [gopro/gpmf-parser#119]
So I got nowhere else to go than here.

I need to contact the GoPro support or furthermore a GoPro software developer.

I work for a german company and we work on a project, where we want to control our Hero 9 Black camera via the new "GoPro Connect" feature. And it mostly works as intended but there is something missing.

We can start (trigger) the camera to start recording via a HTTP request, but we cannot **stop** the recording via a HTTP request.
The HTTP request for stopping the rcording seems not to be implemented.?
Is this intentional? Because on older cameras, the Hero 7 for example, this feature is available (over Wifi).

So, here are two questions:
1. Will this feature get implemented in the future? And when will this be?
2. If there is this HTTP request already implemented and only shifted to an other "address" or renamed, can someone please tell me the new "address" or name.

Thanks, I appreciate all the help I can get.

Yours sincerely.

**Comment by dnewman-gpsw** [comment]
This is known issue / feature.  The HERO9 camera is working harder than earlier cameras (larger sensor is one reason), and can't service all the commands over USB while recording.  We are aware of this limitation, and will be consider workarounds if or when this becomes a public feature.  No promises.
