### ISSUE TITLE
Sample Rate

### ISSUE THREAD

**Issue by sebasdrc** [gopro/gpmf-parser#137]
Is there a way to lower the sample rate for the accelerometers or gyro sensors? For example, if I have a 14 min video (840 seconds) instead of printing 168,000 data points (~202 points per second), can I print 1 data point per second (change the sample rate to 1 Hz).

**Comment by dnewman-gpsw** [comment]
You can downsample to any rate, however that is not a function of the gpmf-parser, which is designed to retrieve the data as it is stored.
