### ISSUE TITLE
Reading gopro data while recording

### ISSUE THREAD

**Issue by zhangy76** [gopro/gpmf-parser#138]
May I if I can directly read the video and telemetry data from a desktop through wifi while recording? Any existing software or API would be very helpful!

Thanks

**Comment by dnewman-gpsw** [comment]
No streaming on GPMF is available, but it is something we have considered adding.

**Comment by trackdaygenius** [comment]
Pleeeeeeeeeze add it, our Motorsport community members keep asking for it. It's become a full time job to reply back, saying not yet...

**Comment by dnewman-gpsw** [comment]
noted.

**Comment by dnewman-gpsw** [comment]
Only closing this as it is not a gpmf-parser bug.  The feature request for the camera is noted.
