### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by sesp94** [gopro/gpmf-parser#147]
Hi,
I use Hero7 (v1.9). In the current documentation it is written that there is a four-cc MAGN... I carrefully browse the STRM but I didn't find any MAGN... so, either I did something wrong, or this information doesn't exist.
Kind regards

**Comment by dnewman-gpsw** [comment]
MAGN is the magnetometer metadata used on our 360 cameras only.  Fusion and MAX camera have a magnetometer, our HERO Line does not. Sorry for the confusion.
