### ISSUE TITLE
Expected data structure

### ISSUE THREAD

**Issue by bcardarella** [gopro/gpmf-parser#153]
I'm writing a parser for Elixir. If you don't mind I'll just dump some questions here.

* Should `DEVC` always be the expected first key?
* Are keys expected to be unique?

**Comment by dnewman-gpsw** [comment]
Yes, DEVC is always first in a valid DEVC payload.  Keys within a DEVC are unique (only have one meaning), however it is possible to have two devices with the same internal data, meaning describing different things.  An example would be a BLE Remote with an Gyro, there could be GYRO data from the camera and GYRO from the remote, all within the one playload.  This is why DEVC = deivce, it is to handle name collisions like this.

**Comment by bcardarella** [comment]
@dnewman-gpsw great, thank you!
