### ISSUE TITLE
Missing timestamp in GoPro metadata

### ISSUE THREAD

**Issue by kuku131** [gopro/gpmf-parser#16]
Hi David,

Hope you had a great weekend!

I have another question regarding the GPS metadata that would appreciate for your help on:
GetGPMFSampleRateAndTimes(ms, 0.0, index, &inTime, &outTime);
Sometimes, the inTime and outTime we retrieve are empty. Can you please advise what might cause this?

Many thanks!

Regards,
Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
Not really enable information here.  Please step through the code and see what fails.

**Comment by kuku131** [comment]
Hi David,

Please check this video and see if you have any idea.
https://www.dropbox.com/sh/g2rjhy71np27puo/AACiMn200qLpPlKbLcWghZHma?dl=0 

Regards,
Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
This capture started before GPS lock.  GPS was even reporting until the fourth seconds, and lock was established until 33 seconds into the capture.   This is all normal.  However, the mp4reader's GetGPMFSampleRate() wasn't handling the delay in the sensor start.  This fix has been pushed.

**Comment by kuku131** [comment]
Thanks David. We will try and let you know how it goes.

**Comment by kuku131** [comment]
Hi David,

With the updated GPMF parser, we are able to retrieve inTime and outTime from the video above. However, we noticed that the GPS timestamp is OUT OF SYNC with the video timestamp. Can you please double check?

Many thanks!

Regards,
Xiaoyue Huo
