### ISSUE TITLE
how to extract gopro mp4 or .360 videos gyro and focal length ( angle of view)

### ISSUE THREAD

**Issue by mcvarer** [gopro/gpmf-parser#164]
I have tried a lot of but i have no solution. i used telemetry, trekview but not found.

I can extract from images these data but don't videos.

such as `Angle of View :  121` or `Field of View : 18mm`

**Comment by dnewman-gpsw** [comment]
Sorry, maybe I don't understand the question, but these are not GPMF data fields.  They look like they might be EXIF data, which is standardized for photos only, video files do not have EXIF.

**Comment by mcvarer** [comment]
Sorry, I would not tell you. 

How to extract field of view  or angle of view from gopro videos?

**Comment by dnewman-gpsw** [comment]
For .360 files the answer is infinite, there is no limit to the FOV.  For HERO style capture in .MP4, the metadata is ZFOV for the diagonal FOV.  Here is a web tool for extracting header (only) GPMF metadata that includes ZFOV https://gopro.github.io/labs/control/metadata/
