### ISSUE TITLE
GPS写入

### ISSUE THREAD

**Issue by yanhui1111** [gopro/gpmf-parser#168]
您好，请问您那个写入GPMF数据的项目可以往视频中写入GPS经度和纬度信息吗？如果可以，请问这个信息是写在了哪里？

**Comment by dnewman-gpsw** [comment]
The gpmf-write is a formatter for storing any media (like GPS) into a track suitable for use within a MP4 or MOV file.  However, is it up to the developer to add the track using third party MP4/MOV writers.

**Comment by yanhui1111** [comment]
您好，请问gpmf-write的输入是一个mp4或者mov的文件吗？
