### ISSUE TITLE
Video and GPS timestamp mismatching

### ISSUE THREAD

**Issue by kuku131** [gopro/gpmf-parser#17]
Hi David,

Hope you are well.

We experienced another issue with the latest GPMF.
With the updated GPMF parser, we are able to retrieve inTime and outTime from the video below. 
https://www.dropbox.com/sh/g2rjhy71np27puo/AACiMn200qLpPlKbLcWghZHma?dl=0

However, we noticed that the GPS timestamp is slightly OUT OF SYNC with the video timestamp. Can you please investigate?

Many thanks for your continuous support!

Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
They agree very well. However, this camera had never received a GPS lock before, which is way the first GPS payloads were filled with zeros, this means the camera has never seen the leap second update which are transmitted from the satellites every few minutes. Read more on a related ticket : https://github.com/gopro/gpmf-parser/issues/6
