### ISSUE TITLE
Segmentation Fault in demo/GPMF_mp4reader.c

### ISSUE THREAD

**Issue by rish9101** [gopro/gpmf-parser#179]
The attached input causes a segmentation fault due to unaddressable access at line 582 in [demo/GPMF_mp4reader.c](https://github.com/gopro/gpmf-parser/blob/5a78b0336ecdfaccc7019557263ae9113567ae71/demo/GPMF_mp4reader.c#LL582C1-L582C1). 

The bug has been tested on Ubuntu 20.04
[unaddressable-access.zip](https://github.com/gopro/gpmf-parser/files/11806489/unaddressable-access.zip)

**Comment by dnewman-gpsw** [comment]
These are cool finds. I have crudely patched them. Fortunately, this demo code is not part of the GPMF parser, it is only to provide a light weight MP4 reader so the GPMF can be accessed. As the file header indicates "Way Too Crude MP4|MOV reader". It is super lightweight and not robust. I just didn't want experimenters to have to deal with FFMPEG in their learning process (and I too didn't want to learn FFMPEG either.)

However if you do want to find more, I happy to attempt to patch them.
