### ISSUE TITLE
Structure of `gpmd` boxes

### ISSUE THREAD

**Issue by bradh** [gopro/gpmf-parser#185]
https://github.com/gopro/gpmf-parser?tab=readme-ov-file#inside-the-meta-track identifies that `gpmd` is a box (under `gmhd`) and a sample entry (under `stsd`). Is the content of those intended to be meaningful, or is it more of a flag value?

I only did light checking, but it looks like it is just a 32 bit value set to 0 (or possibly they are version 0x00 and flags 0x00 0x00 0x00, as in a FullBox structure, and there is no body). Just want to make sure my checks are rigorous enough....

**Comment by dnewman-gpsw** [comment]
That is nothing on importance stored in the headers.  Metadata tracks in MP4s were not common when GPMF was introduced, GoPro was the to use this method.  Other than indexing, all the data in the required data is in the track (within the mdat.)

**Comment by bradh** [comment]
Thanks.
