### ISSUE TITLE
Fusion Gyro data Firmware v1.609

### ISSUE THREAD

**Issue by gyromodel** [gopro/gpmf-parser#25]
I'm unable to get the Gyro/Accl/GPS data from a GoPro fusion capture. I'm able to see ISOG and SHUT data, but not Gyro. Has anything changed in the firmware for this to happen?

**Comment by dnewman-gpsw** [comment]
Internally Fusion has two SoCs (System on Chip) for capture and compressing data, very like two Hero5s in one package.  However it only has one GPS receiver and IMU, both hooked to the front camera (GPFRxxxx.MP4.)  You will see ISOG and SHUT on both cameras as that data is independent, we need to know exposure differences between front and back cameras.  So for IMU/GPS data use the front camera media.
