### ISSUE TITLE
Where is camera serial number located?

### ISSUE THREAD

**Issue by jin-zhe** [gopro/gpmf-parser#28]
Hi I'm using multiple GoPro Hero 5s in my current project and I'd like to extract the camera serial number to differentiate footages from different camera. How might I extract the camera serial number from the GPMD?

EDIT:
I realized it's captured within the `fdsc` and not the `gpmd` stream

**Comment by dnewman-gpsw** [comment]
the 'udta' (the user data atom) contains the classic metadata ever since HERO2. It has FIRM for firmware version, CAME for camera serial/ID, LENS for lens model/vendor/batch, MUID Media Unique ID, GUMI Global Unique Media Id,  HMMT Hightlight moments.  The details of these are outside of GPMF.

**Comment by jin-zhe** [comment]
Thanks @dnewman-gpsw ! Where and how do I go about obtaining the udta? I don't see it in any of the streams
