### ISSUE TITLE
Create and insert gopro data into a non gopro video

### ISSUE THREAD

**Issue by Muvuk** [gopro/gpmf-parser#3]
Hi,

Gopro Quik (desktop) allows edit only gopro files. (Compatible with footage captured using HERO5 Black with GPS activated.)  Is there a way to create gopro video from another video? Can we create and insert some gopro data?

I think we need something similar like this: 
https://support.google.com/jump/answer/7044297?hl=en

What do you think? Is it possible?

**Comment by dnewman-gpsw** [comment]
Yes this is possible, although this repo doesn't provide that ability (it is reader not a writer), it does provide the knowhow for anything knowledgeable enough with MP4 creation / rewrapping.
