### ISSUE TITLE
Is there a way to detect how the camera is mounted?

### ISSUE THREAD

**Issue by kuku131** [gopro/gpmf-parser#34]
Hi David,

Hope all is well.

I have a quick question that would appreciate for your help on:
Is there a way to detect how the GoPro camera is mounted? If the camera is mounted to face reverse, the 3-axis accelerometer and 3-axis gyroscope would go completely wrong. How can this be detected and handled?

Many thanks!

Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
I'm not sure what you mean by IMU data being wrong.  It is always relative to the lens, so you can determine the camera orientation from the IMU data.  A mounted camera is typically under the influence of gravity, so that direction is known.

**Comment by kuku131** [comment]
Hi David,

Thanks for your response!

Please see below example screen shot, my GoPro camera was mounted to face reverse. This way, the IMU.X and IMU.Y data are wrong way around. E.g: X = -X and Y = -Y. Can you please advise if there is a way to detect this?
![capture](https://user-images.githubusercontent.com/835674/44788374-c6e05b80-ab91-11e8-9682-42c0c0f31136.PNG)

**Comment by kuku131** [comment]
I meant accel.x and accel.y are wrong way around, if the GoPro camera is mounted in the way shown in my above screen shot.
Please let me know if there is a way to detect it so that we can handle this in our app.

Thanks!

Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
My understanding is this requires a sensor fusion solution.  From the IMU data you can determine a crude motion path, match that path to the GPS data and you will know the camera's orientation.

**Comment by kuku131** [comment]
Thanks for the clarification David. :)
