### ISSUE TITLE
Orentation in hero 5 metadata?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [gopro/gpmf-parser#40]
Thanks for help with detecting the FOV.  
Now I'm looking for the camera's orientation (whether its set to "up" "down" or "auto" in the preferences and what orientation it ended up in while recording).  I tried looking at the bit-field in the SETT atom and I found the the bit that says if gravity matches camera orientation.  But this doesn't actually tell me what orientation the camera was in while recording.  For example, when camera's orientation is set to "auto" in the preferences the bit in the SETT atom will always be off/0 regardless of the actual camera orientation when rec was pressed.  
Thanks again for all your help!

**Comment by dnewman-gpsw** [comment]
We do not store that data.   You could use the ACCL data and be 99% correct.
