### ISSUE TITLE
Calculating Lean Angle using GYRO

### ISSUE THREAD

**Issue by kuku131** [gopro/gpmf-parser#45]
Hi David,

Hope all is well!

May I know if it is possible to calculate lean angle using GYRO data when GoPro camera is mounted on a bike? If yes, how does it work?

Many thanks!

Xiaoyue Huo

**Comment by dnewman-gpsw** [comment]
Full camera orientation can be determined from GYRO and ACCL streams, as this is all Fusion uses to do its awesome stabilization.  However stabilization is only concerned with changing camera orientation, not absolute angles relative to the ground.   I don't have any sample code I can share to compute the lean angle, but I believe it can be done.  One way to do it would be to compute the lateral acceleration from GPS position and compare with the acceleration direction measured from the ACCL data, the difference will help you compute lean angle.
