### ISSUE TITLE
Documentation for FourCC "SROT"

### ISSUE THREAD

**Issue by BocDrown** [gopro/gpmf-parser#48]
Hi there,

thanks an awful lot for making this protocol public! I'm just curious about the content of the SROT stream I found in my Hero7 Black's gpmf stream as I couldn't find it in the documentation.

Thanks and happy holidays!
Jan-Philipp

**Comment by dnewman-gpsw** [comment]
It is supposed to be Sensor Read Out Time in milliseconds, but it is wrong for two reasons (the bug filed in the camera.)  
1) The SROT value is constant, as it should be throughout a video capture, as each mode only has a single SROT value.  Therefore SROT should not have been stored in the GPMF track, rather it should have been a single value in the 'udta' header.  
2) The data it stores is often wrong.
