### ISSUE TITLE
easy way to make the demo print out or export gps5 data ?

### ISSUE THREAD

**Issue by tavdog** [gopro/gpmf-parser#49]
It's amazing that I actually got this to compile but the demo doesn't really do anything. I'm trying to use this to get gps data out of gopro video files.

**Comment by dnewman-gpsw** [comment]
The demo code defaults to outputting the GPS data.  It current shows the first payload of GPS data, for all the payload uncomment line 177 of GPMF_demo.c.

You will see when run (assuming your source file has GPS):
  STRM of ACCL of type s with 249 samples -- 3 elements per sample
  STRM of GYRO of type s with 249 samples -- 3 elements per sample
  STRM of GPS5 of type l with 23 samples -- 5 elements per sample
  STRM of ISOE of type L with 30 samples
  STRM of SHUT of type f with 30 samples
  STRM of WBAL of type S with 10 samples
  STRM of WRGB of type f with 10 samples -- 3 elements per sample
  STRM of YAVG of type B with 10 samples
  STRM of UNIF of type f with 10 samples
  STRM of SCEN of type Ff with 10 samples -- 2 elements per sample
  STRM of HUES of type BB with 10 samples -- 2 elements per sample
  STRM of SROT of type f with 30 samples

MP4 Payload time 0.000 to 1.001 seconds
GPS5 34.087deg, -117.501deg, 308.462m, 0.183m/s, 0.230m/s,
GPS5 34.087deg, -117.501deg, 308.452m, 0.159m/s, 0.200m/s,
GPS5 34.087deg, -117.501deg, 308.439m, 0.169m/s, 0.170m/s,
GPS5 34.087deg, -117.501deg, 308.428m, 0.209m/s, 0.180m/s,
GPS5 34.087deg, -117.501deg, 308.429m, 0.232m/s, 0.220m/s,
GPS5 34.087deg, -117.501deg, 308.417m, 0.223m/s, 0.240m/s,
GPS5 34.087deg, -117.501deg, 308.415m, 0.214m/s, 0.230m/s,
GPS5 34.087deg, -117.501deg, 308.422m, 0.207m/s, 0.220m/s,
GPS5 34.087deg, -117.501deg, 308.422m, 0.245m/s, 0.210m/s,
GPS5 34.087deg, -117.501deg, 308.425m, 0.234m/s, 0.250m/s,
GPS5 34.087deg, -117.501deg, 308.426m, 0.210m/s, 0.240m/s,
GPS5 34.087deg, -117.501deg, 308.420m, 0.153m/s, 0.210m/s,
GPS5 34.087deg, -117.501deg, 308.408m, 0.151m/s, 0.160m/s,
GPS5 34.087deg, -117.501deg, 308.367m, 0.218m/s, 0.160m/s,
GPS5 34.087deg, -117.501deg, 308.318m, 0.204m/s, 0.220m/s,
GPS5 34.087deg, -117.501deg, 308.273m, 0.262m/s, 0.210m/s,
GPS5 34.087deg, -117.501deg, 308.270m, 0.274m/s, 0.260m/s,
GPS5 34.087deg, -117.501deg, 308.303m, 0.295m/s, 0.280m/s,
GPS5 34.087deg, -117.501deg, 308.365m, 0.277m/s, 0.300m/s,
GPS5 34.087deg, -117.501deg, 308.459m, 0.175m/s, 0.280m/s,
GPS5 34.087deg, -117.501deg, 308.538m, 0.198m/s, 0.180m/s,
GPS5 34.087deg, -117.501deg, 308.616m, 0.197m/s, 0.200m/s,
GPS5 34.087deg, -117.501deg, 308.666m, 0.195m/s, 0.200m/s,

MP4 Payload time 1.001 to 2.002 seconds
GPS5 34.087deg, -117.501deg, 308.712m, 0.176m/s, 0.200m/s,
GPS5 34.087deg, -117.501deg, 308.749m, 0.137m/s, 0.180m/s,
GPS5 34.087deg, -117.501deg, 308.782m, 0.087m/s, 0.140m/s,
GPS5 34.087deg, -117.501deg, 308.815m, 0.109m/s, 0.090m/s,
GPS5 34.087deg, -117.501deg, 308.831m, 0.158m/s, 0.110m/s,
GPS5 34.087deg, -117.501deg, 308.841m, 0.162m/s, 0.160m/s,
GPS5 34.087deg, -117.501deg, 308.849m, 0.136m/s, 0.160m/s,
GPS5 34.087deg, -117.501deg, 308.863m, 0.105m/s, 0.140m/s,
GPS5 34.087deg, -117.501deg, 308.844m, 0.136m/s, 0.110m/s,
GPS5 34.087deg, -117.501deg, 308.821m, 0.215m/s, 0.140m/s,
GPS5 34.087deg, -117.501deg, 308.785m, 0.243m/s, 0.210m/s,
GPS5 34.087deg, -117.501deg, 308.765m, 0.272m/s, 0.240m/s,
GPS5 34.087deg, -117.501deg, 308.763m, 0.240m/s, 0.270m/s,
GPS5 34.087deg, -117.501deg, 308.777m, 0.261m/s, 0.240m/s,
GPS5 34.087deg, -117.501deg, 308.784m, 0.202m/s, 0.260m/s,
GPS5 34.087deg, -117.501deg, 308.807m, 0.147m/s, 0.200m/s,
GPS5 34.087deg, -117.501deg, 308.844m, 0.142m/s, 0.150m/s,
GPS5 34.087deg, -117.501deg, 308.916m, 0.147m/s, 0.150m/s,
GPS5 34.087deg, -117.501deg, 308.960m, 0.191m/s, 0.180m/s,

etc..
