### ISSUE TITLE
Define how to carry GPMF in the DASH ingest protocol specification

### ISSUE THREAD

**Issue by johndeu** [gopro/gpmf-parser#50]
Hi GoPro team, 
The DASH industry forum is in the process of writing a new DASH ingest protocol specification and we would be very interested in working with GoPro to update the spec to support timed metadata in GPMF format so that it could be carried outbound in DASH and HLS using the CMAF 'emsg' MP4 box. 

To support this we would need an official documented schemeID URI for the GoPro metadata format and some examples of how to carry it in 'emsg' or in-band with DASH.  

Is there someone on the GoPro team that can contribute to the DASH ingest specification here:
https://github.com/Dash-Industry-Forum/Ingest/ 

Contact me directly if you have questions.

**Comment by dnewman-gpsw** [comment]
Happy to be involved.
