### ISSUE TITLE
Can't find GPSU data

### ISSUE THREAD

**Issue by jlevers** [gopro/gpmf-parser#57]
When I try to pull out GPSU data, which from what I've read should be in the GPS5 stream, I don't get any data. For instance, adding the condition 

`GPMF_OK == GPMF_FindNext(ms, STR2FOURCC("GPSU"), GPMF_RECURSE_LEVELS)`

 to [line 179](https://github.com/gopro/gpmf-parser/blob/master/demo/GPMF_demo.c#L179) of `GPMF_demo.c` doesn't result in any additional data being printed out when I make and run the program.

Any thoughts as to why this would be? Am I misunderstanding how GPSU data is stored? Thank you!

**Comment by dnewman-gpsw** [comment]
That change will find it the GPSU, however the sample code below is not set up to print it (it will print array of floats.)  Here is a snippet that works: 

if (GPMF_OK == GPMF_FindNext(ms, STR2FOURCC("GPSU"), GPMF_RECURSE_LEVELS))
{
	uint32_t key = GPMF_Key(ms);
	char GSPU[17];

	GPMF_FormattedData(ms, GSPU, 16, 0, 1);
	GSPU[16] = 0;
	printf("%c%c%c%c %s\n", PRINTF_4CC(key), GSPU);
}

**Comment by jlevers** [comment]
Oh, of course -- that was silly of me. Thanks!

**Comment by StevePhan101** [comment]
Hi David @dnewman-gpsw,
I have followed the sampled code and extracted the timestamp: 200728022523.869.
How can I convert this unix timestamp (in seconds I guess) to human date (2020/07/29 for example)?
Thank you.
