### ISSUE TITLE
Incorrect data in hero6+ble.mp4 sample?

### ISSUE THREAD

**Issue by JuanIrache** [gopro/gpmf-parser#61]
Hi David,

I can read pretty much all GPMF values with my JavaScript parser, but the sample file **hero6+ble.mp4** produces some strange results in the main device (Hero6 Black) streams. There are a couple of nests that only contain the STNM, and nothing else. They are "Auto Low Light frame Duration" and "3A STATS". I'm wondering if this is an issue with the sample data or it could point at a problem with my interpretation.

Here's some of the output, where { "STNM": "3A STATS" } appears to be surrounded by correct data, but it has no values, total samples or anything else.

```
{
          "TSMP": 132,
          "STNM": "Face Coordinates and details",
          "TYPE": "Lffff",
          "FACE": [null, null, null, null, null, null, null, null, null, null, null, null]
        },
        { "TSMP": 132, "STNM": "Face numbers", "FCNM": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
        { "STNM": "3A STATS" },
        {
          "TSMP": 264,
          "STNM": "Sensor ISO",
          "ISOE": [510, 508, 501, 494, 489, 484, 481, 478, 475, 472, 469, 463, 457, 453, 447, 443, 439, 435, 431, 428, 426, 422, 421, 419]
        },
```
And this is the parent snippet:
`{ fourCC: 'STRM', type: '\u0000', size: 1, repeat: 20 }`

Thank you

**Comment by dnewman-gpsw** [comment]
You are reading it correctly.  I expect "3A STATS" was some leftover debug code in HERO6, I never seen it carry any data.  The "Auto Low Light frame Duration" was a minor bug in HERO6, is was only supposed to show that field (with data) is you used a mode in which the auto low-light was applied.
