### ISSUE TITLE
add hero7 and hero8 sample data

### ISSUE THREAD

**Issue by nzjrs** [gopro/gpmf-parser#79]
thanks. would be helpful for validation and testing

**Comment by dnewman-gpsw** [comment]
I will be adding 7, 8 and MAX shortly

**Comment by dnewman-gpsw** [comment]
All video modes on MAX have GPMF.  TimeWarp is a video mode.

**Comment by nzjrs** [comment]
@dnewman-gpsw sorry can we keep this issue open until the sample files are committed?

**Comment by nzjrs** [comment]
for those subscribed to this bug the new samples were added with https://github.com/gopro/gpmf-parser/commit/9958d833d76d33d7a396e6da3beb3d6dfdfb74dd

- me, a human, taking jobs back from the AI

p.s. this is why closing issues with commits is preferred
