### ISSUE TITLE
DISP for gopro max

### ISSUE THREAD

**Issue by hit2sjtu** [gopro/gpmf-parser#87]
Are there any documents on DISP for gopro max?

**Comment by dnewman-gpsw** [comment]
From the readme:
DISP | Disparity track (360 modes) | frame rate | n/a | 1-D depth map for the objects seen by the two lenses

While the is stored in both the .LRV and .360, it is only used for previewing the LRVs.  LRVs are not stitched, and .360 are.  So the camera has already computed the depth map for stitching near and far objects that cross the stitch line for the .360 files, this is stored as DISP.   DISP is used so the preview more closely matches the full resolution output.  This data doesn't have much other application.
